"""
File used for testing and running our production code 
"""


# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
load("group_characters.sage")
load("suzuki_characters.sage")
load("psu_characters.sage")
load("helper_functions.sage")
#G = GroupCharacters("PSU(3, 5)")
# print(G.the_game(G.characters[1]))
for j in [_sage_const_4 , _sage_const_5 , _sage_const_7 , _sage_const_8 , _sage_const_9 , _sage_const_11 , _sage_const_13 ]:
    G = PSU_Characters(_sage_const_2 , j)
    print(_sage_const_2 , j)
    for h in range(len(G.characters)):
        print(h)
        print(generators_from_molien(G.molien_coeff(G.characters[h], _sage_const_8 )))
        print(G.minimal_perm)
for j in [_sage_const_3 ,_sage_const_4 ,_sage_const_5 ,_sage_const_7 ]:
    G = PSU_Characters(_sage_const_3 , j)
    print(_sage_const_3 , j)
    print(generators_from_molien(G.molien_coeff(G.characters[_sage_const_0 ], _sage_const_8 )))
    print(generators_from_molien(G.molien_coeff(G.characters[_sage_const_1 ], _sage_const_8 )))
    print(generators_from_molien(G.molien_coeff(G.characters[_sage_const_2 ], _sage_const_8 )))
    print(generators_from_molien(G.molien_coeff(G.characters[_sage_const_3 ], _sage_const_8 )))
    #print(G.the_game(G.characters[1]))
    #print(G.the_game(G.characters[2]))
    #print(G.the_game(G.characters[3]))
    print(G.minimal_perm)
for j in [_sage_const_3 ,_sage_const_4 ,_sage_const_5 ]:
    for i in range(_sage_const_4 , _sage_const_7 ):
        print(i, j)
        G = PSU_Characters(i, j)
        print(G.the_game(G.characters[_sage_const_1 ]))
        print(G.the_game(G.characters[_sage_const_2 ]))
        print(G.the_game(G.characters[_sage_const_3 ]))
        print(G.minimal_perm)
# G = PSU_Characters(2, 8)
# print(G.characters)
# print(G.the_game(G.characters[1]))
# print(G.the_game(G.characters[2]))
"""
for j in [9, 13, 19, 25, 27, 31]:
    G = PSU_Characters(3, j)
    print(3, j)
    print(G.the_game(G.characters[1]))
    print(G.the_game(G.characters[2]))
    print(G.the_game(G.characters[3]))
    print(G.minimal_perm)
"""

