"""
A collection of combinatorial power maps that allow for the general (i.e., in terms of q) calculation of the dimension of the 2nd, 3rd, and 
4th Symmetric powers of the smallest non-trivial irreducible representation of PSU(3,q).
"""


# This file was *autogenerated* from the file PSL_General_Sym_test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_12 = Integer(12); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_8 = Integer(8); _sage_const_24 = Integer(24); _sage_const_36 = Integer(36); _sage_const_72 = Integer(72)
from sympy import sympify


class sym_object: 
    def __init__(self, modulus, power):
        self.power = power
        self.modulus = modulus
        self.q = var('q')
        self.d = gcd(_sage_const_3 , self.modulus - _sage_const_1 )
        self.r = self.q-_sage_const_1 
        self.s = self.q+_sage_const_1  
        self.t = self.q**_sage_const_2  + self.q + _sage_const_1 
        self.rp = self.r/self.d
        self.sp = self.s/self.d
        self.tp = self.t/self.d
        self.dp = (_sage_const_3 -self.d)/_sage_const_2 
        self.rpp = self.rp
        self.tpp = (self.tp - _sage_const_1 )/_sage_const_6  

        self.families = ['1', '2', '3^l', '4^k', '5^k', "6'", "6^klm", "7^k", "8^k"]
        self.num_classes = {'1': _sage_const_1 , '2': _sage_const_1 , '3^l': self.d, '4^k': self.rp - _sage_const_1 , '5^k': self.rp - _sage_const_1 , "6'": _sage_const_1  - self.dp, "6^klm": self.tpp - self.rpp, "7^k": self.tpp - self.rpp - self.dp, "8^k": _sage_const_2 *self.tpp}
        self.centralizers = {'1': self.q**_sage_const_3  * self.rp * self.r * self.s * self.t, '2': self.q**_sage_const_3  * self.rp, '3^l': self.q**_sage_const_2 , '4^k': self.q*self.rp*self.r*self.s, '5^k': self.q*self.rp, "6'": self.r**_sage_const_2 , "6^klm": self.rp*self.r, "7^k": self.rp*self.s, "8^k": self.tp}
        self.class_sizes = {key: (self.q**_sage_const_3  * self.rp * self.r * self.s * self.t) / val for key, val in self.centralizers.items()}
        self.character_val = {'1': self.q*self.s, '2': self.q, '3^l': _sage_const_0 , '4^k': self.s, '5^k': _sage_const_1 , "6'": _sage_const_2 , "6^klm": _sage_const_2 , "7^k": _sage_const_0 , "8^k": -_sage_const_1 }
    
    def C_1_power(self):
        if self.power == _sage_const_2 :
            C1Counter = _sage_const_1 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
        if self.power == _sage_const_3 :
            C1Counter = _sage_const_1 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
        if self.power == _sage_const_4 :
            C1Counter = _sage_const_1 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_2_power(self):
        if self.power == _sage_const_2 :
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_1 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            if self.modulus % _sage_const_2  == _sage_const_0 :
                C1Counter += _sage_const_1 
                C2Counter -= _sage_const_1 
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
        if self.power == _sage_const_3 :
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_1 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            if self.modulus % _sage_const_3  == _sage_const_0 :
                C1Counter += _sage_const_1 
                C2Counter -= _sage_const_1 
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
        if self.power == _sage_const_4 :
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_1 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            if self.modulus % _sage_const_2  == _sage_const_0 :
                C1Counter += _sage_const_1 
                C2Counter -= _sage_const_1 
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_3_power(self):
        if self.power == _sage_const_2 :
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_0 
            C3Counter = self.d
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            if self.modulus % _sage_const_2  == _sage_const_0 :
                C2Counter += self.d
                C3Counter -= self.d
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
        if self.power == _sage_const_3 :
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_0 
            C3Counter = self.d
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            if self.modulus % _sage_const_3  == _sage_const_0 :
                C1Counter += self.d
                C3Counter -= self.d
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
        if self.power == _sage_const_4 :
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_0 
            C3Counter = self.d
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            if self.modulus % _sage_const_2  == _sage_const_0 :
                C1Counter += self.d
                C3Counter -= self.d
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_4_power(self):
        if self.power == _sage_const_2 :
            C1Counter = _sage_const_0 
            C4Counter = (self.r)/self.d-_sage_const_1 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            if self.modulus % _sage_const_2  == _sage_const_1 :
                C1Counter += _sage_const_1 
                C4Counter -= _sage_const_1 
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

        if self.power == _sage_const_3 :
            C1Counter = _sage_const_0 
            C4Counter = (self.r)/self.d-_sage_const_1 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            if (self.modulus - _sage_const_1 ) % _sage_const_9  == _sage_const_0 : # going to need the mod we're dealing with to be divisible by 9
                C1Counter += _sage_const_2 
                C4Counter -= _sage_const_2 
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

        if self.power == _sage_const_4 :
            C1Counter = _sage_const_0 
            C4Counter = (self.r)/self.d-_sage_const_1 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            if (self.modulus - _sage_const_1 ) % _sage_const_4  == _sage_const_0 : 
                C1Counter += _sage_const_3 
                C4Counter -= _sage_const_3 
            elif (self.modulus - _sage_const_1 ) % _sage_const_2  == _sage_const_0 :
                C1Counter += _sage_const_1 
                C4Counter -= _sage_const_1 
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_5_power(self):
        if self.power == _sage_const_2 :
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = (self.r)/self.d-_sage_const_1 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            if self.modulus % _sage_const_2  == _sage_const_1 :
                C2Counter +=_sage_const_1 
                C5Counter -= _sage_const_1 
            if self.modulus % _sage_const_2  == _sage_const_0 :
                C4Counter += (self.r)/self.d-_sage_const_1 
                C5Counter -= (self.r)/self.d-_sage_const_1 
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
        if self.power == _sage_const_3 :
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = (self.r)/self.d-_sage_const_1 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            if (self.modulus-_sage_const_1 ) % _sage_const_9  == _sage_const_0 : # need self.modulus divisible by 9
                C2Counter += _sage_const_2 
                C5Counter -= _sage_const_2 
            if self.modulus % _sage_const_3  == _sage_const_0 :
                C4Counter += (self.r)/self.d-_sage_const_1 
                C5Counter-= (self.r)/self.d-_sage_const_1  
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

        if self.power == _sage_const_4 :
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = (self.r)/self.d-_sage_const_1 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            if (self.modulus-_sage_const_1 ) % _sage_const_2  == _sage_const_0 :
                C2Counter += _sage_const_1 
                C5Counter -= _sage_const_1 
            if (self.modulus-_sage_const_1 ) % _sage_const_4  == _sage_const_0 :
                C2Counter += _sage_const_2 
                C5Counter -= _sage_const_2 
            if self.modulus % _sage_const_2  == _sage_const_0 :
                C4Counter += (self.r)/self.d-_sage_const_1 
                C5Counter-= (self.r)/self.d-_sage_const_1  
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_6_p_power(self):
        if self.power == _sage_const_2 :
            C6pCounter = _sage_const_1 -(_sage_const_3 -self.d)/_sage_const_2 
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
        if self.power == _sage_const_3 :
            C6pCounter = _sage_const_0 
            C1Counter = _sage_const_1 -(_sage_const_3 -self.d)/_sage_const_2 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
        if self.power == _sage_const_4 :
            C6pCounter = _sage_const_1 -(_sage_const_3 -self.d)/_sage_const_2 
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_0 
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_6_klm_power(self):
        if self.power == _sage_const_2 :
            if (self.modulus-_sage_const_1 ) % _sage_const_12  in [_sage_const_1 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_9 ,_sage_const_11 ]:
                C4Counter = _sage_const_0  
            if (self.modulus-_sage_const_1 ) % _sage_const_12  in [_sage_const_2 , _sage_const_10 ]:
                total = _sage_const_0  - ceil(self.r/_sage_const_4 ) + floor(self.r/_sage_const_6 ) + self.r/_sage_const_2   + ceil(floor(self.r/_sage_const_6 )/_sage_const_2 )
                C4Counter = total
            if (self.modulus-_sage_const_1 ) % _sage_const_12  in [_sage_const_4 , _sage_const_8 ]:
                total = -_sage_const_1  * floor(self.r/_sage_const_4 ) + floor(self.r/_sage_const_6 ) + self.r/_sage_const_2  + floor((ceil(self.r/_sage_const_6 ) - _sage_const_1 )/_sage_const_2 )
                C4Counter = total
            if (self.modulus-_sage_const_1 ) % _sage_const_12  == _sage_const_6 :
                C4Counter = self.r/_sage_const_6  - _sage_const_1 
            if (self.modulus-_sage_const_1 ) % _sage_const_12  == _sage_const_0 :
                C4Counter = self.r/_sage_const_6  - _sage_const_1  
            return (_sage_const_0 , _sage_const_0 , _sage_const_0 , C4Counter, _sage_const_0 , _sage_const_0 , self.tpp - self.rpp - C4Counter, _sage_const_0 , _sage_const_0 )

        if self.power == _sage_const_3 :
            C4Counter = _sage_const_0 
            a = (self.modulus - _sage_const_1 ) % _sage_const_12 
            if a%_sage_const_3  != _sage_const_0 :
                pass
            if a%_sage_const_6  == _sage_const_0 :
                # Case 2a
                C4Counter +=  (ceil(_sage_const_2 *self.r/_sage_const_9 ) - _sage_const_1 ) - ceil(self.r/_sage_const_6 ) + _sage_const_1 
                # Case 3a
                C4Counter += floor((ceil(_sage_const_2 *self.r/_sage_const_9 ) - _sage_const_1 )/_sage_const_2 )
                # Case 2a, 3a diff of 2r/3
                C4Counter += ceil(self.r/_sage_const_9 ) - _sage_const_1  
                C4Counter += floor((ceil(self.r/_sage_const_9 ) - _sage_const_1 )/_sage_const_2 )

            if a%_sage_const_6  == _sage_const_3 :
                # Case 2a
                C4Counter += (ceil(_sage_const_2 *self.r/_sage_const_9 ) - _sage_const_1 ) - ceil(self.r/_sage_const_6 ) + _sage_const_1 
                # Case 3a
                C4Counter += floor((ceil(_sage_const_2 *self.r/_sage_const_9 ) - _sage_const_1 )/_sage_const_2 )
                # Case 2a, 3a diff of 2r/3
                C4Counter += ceil(self.r/_sage_const_9 ) - _sage_const_1    
                C4Counter += ceil((ceil(self.r/_sage_const_9 ) - _sage_const_1 )/_sage_const_2 )
            return (_sage_const_0 , _sage_const_0 , _sage_const_0 , C4Counter, _sage_const_0 , _sage_const_0 , self.tpp - self.rpp - C4Counter, _sage_const_0 , _sage_const_0 )

        if self.power == _sage_const_4 :
            C4Counter = _sage_const_0 
            C1Counter = _sage_const_0 
            a = (self.modulus - _sage_const_1 ) % _sage_const_24  
            square_modulus = self.modulus % _sage_const_12 
            square_sym = sym_object(square_modulus, _sage_const_2 ) 
            C4Counter += square_sym.C_6_klm_power()[_sage_const_3 ]
            if a % _sage_const_4  != _sage_const_0 :
                pass
            elif a % _sage_const_3  != _sage_const_0 :
                # Case 1a
                C4Counter += ceil(self.r/_sage_const_6 ) - _sage_const_1 
                # Case 1b
                C4Counter += ceil(self.r/_sage_const_2 ) - _sage_const_1  - ceil(_sage_const_3 *self.r/_sage_const_8 ) + _sage_const_1 
                # Case 2a
                C4Counter += ceil(self.r/_sage_const_4 ) - _sage_const_1  - ceil(self.r/_sage_const_6 ) + _sage_const_1 
                # Case 2b
                C4Counter += ceil(_sage_const_7 *self.r/_sage_const_12 ) - _sage_const_1  - (floor(self.r/_sage_const_2 ) + _sage_const_1 ) + _sage_const_1  
                # Case 3a 
                if a % _sage_const_8  == _sage_const_0 :
                    C4Counter += floor((ceil(self.r/_sage_const_4 ) - _sage_const_1 )/_sage_const_2 )
                if a % _sage_const_8  == _sage_const_4 :
                    C4Counter += ceil((ceil(self.r/_sage_const_4 ) - _sage_const_1 )/_sage_const_2 )
                # Case 3b
                if a % _sage_const_8  == _sage_const_0 :
                    C4Counter += ceil((ceil(self.r*_sage_const_7 /_sage_const_12 ) - _sage_const_1  - ceil(self.r/_sage_const_4 ) + _sage_const_1 )/_sage_const_2 )
                if a % _sage_const_8  == _sage_const_4 :
                    C4Counter += ceil((ceil(self.r*_sage_const_7 /_sage_const_12 ) - _sage_const_1  - ceil(self.r/_sage_const_4 ) + _sage_const_1 )/_sage_const_2 )
                # diff of 3r/4
                # Case 1b
                C4Counter += ceil(self.r/_sage_const_6 ) - _sage_const_1  - ceil(self.r/_sage_const_8 ) + _sage_const_1  
                # Case 2a
                C4Counter += ceil(self.r/_sage_const_12 ) - _sage_const_1 
                # Case 2b
                C4Counter += ceil(self.r/_sage_const_4 ) - ceil(self.r/_sage_const_6 ) + _sage_const_1  
                # Case 3a
                if a % _sage_const_8  == _sage_const_0 :
                    C4Counter += floor(floor(self.r/_sage_const_12 )/_sage_const_2 )
                elif a % _sage_const_8  == _sage_const_4 :
                    C4Counter += ceil(floor(self.r/_sage_const_12 )/_sage_const_2 )
                C4Counter -= _sage_const_3 
                C1Counter += _sage_const_1 
            elif a % _sage_const_3  == _sage_const_0 :
                # Case 1a 
                C4Counter += ceil(self.r/_sage_const_12 )
                # Case 2a
                C4Counter += ceil(self.r/_sage_const_4 ) - _sage_const_1  - ceil(_sage_const_5 *self.r/_sage_const_24 ) + _sage_const_1 
                # Case 3a
                if a % _sage_const_8  == _sage_const_0 :
                    C4Counter += floor((ceil(self.r/_sage_const_4 ) - _sage_const_1  - ceil(self.r/_sage_const_12 ) + _sage_const_1 )/_sage_const_2 )
                elif a % _sage_const_8  == _sage_const_4 :
                    C4Counter += ceil((ceil(self.r/_sage_const_4 ) - _sage_const_1  - ceil(self.r/_sage_const_12 ) + _sage_const_1 )/_sage_const_2 )
                # diff of 3r/4
                # Case 2a
                C4Counter += ceil(self.r/_sage_const_12 ) - _sage_const_1 
                # Case 3a 
                if a % _sage_const_8  == _sage_const_0 :
                    C4Counter += floor(floor(self.r/_sage_const_12 )/_sage_const_2 )
                elif a % _sage_const_8  == _sage_const_4 :
                    C4Counter += ceil(floor(self.r/_sage_const_12 )/_sage_const_2 )
                C4Counter -= _sage_const_4 
                C1Counter += _sage_const_1 
            return (C1Counter, _sage_const_0 , _sage_const_0 , C4Counter, _sage_const_0 , _sage_const_0 , self.tpp - self.rpp - C4Counter - C1Counter, _sage_const_0 , _sage_const_0 )

    def C_7_power(self):
        if self.power == _sage_const_2 :
            totalnum = (_sage_const_3 *self.tpp - self.rpp - self.dp) 
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = totalnum
            C8Counter = _sage_const_0 
            if self.modulus % _sage_const_2  != _sage_const_0 :
                C4Counter += (self.r)/(_sage_const_2 *self.d)
                C7Counter = C7Counter - (self.r)/(_sage_const_2 *self.d)
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

        if self.power == _sage_const_3 :
            totalnum = (_sage_const_3 *self.tpp - self.rpp - self.dp)
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = totalnum
            C8Counter = _sage_const_0 
            if self.modulus % _sage_const_3  == _sage_const_1 :
                C1Counter += _sage_const_1 
                C7Counter -= _sage_const_1 
                C4Counter += self.q
                C7Counter -= self.q
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

        if self.power == _sage_const_4 :
            totalnum = (_sage_const_3  * self.tpp) - self.rpp - (_sage_const_3 -self.d)/_sage_const_2 
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = totalnum
            C8Counter = _sage_const_0 
            if self.modulus % _sage_const_2  == _sage_const_1 :
                C4Counter += (self.r)/(_sage_const_2 *self.d)
                C7Counter -= (self.r)/(_sage_const_2 *self.d)
            if (self.modulus-_sage_const_1 )%_sage_const_2  == _sage_const_0  and (self.modulus-_sage_const_1 )%_sage_const_4  != _sage_const_0 :
                C1Counter += _sage_const_1 
                C4Counter -= _sage_const_1 
            if self.modulus % _sage_const_4  == _sage_const_1 :
                C4Counter += _sage_const_2 *(self.r)/(_sage_const_2 *self.d) # why do we have a 2 in the numerator and denominator?
                C7Counter -= _sage_const_2 *(self.r)/(_sage_const_2 *self.d)
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_8_power(self):
        if self.power == _sage_const_2 :
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_2  * self.tpp
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

        if self.power == _sage_const_3 :
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_2  * self.tpp
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

        if self.power == _sage_const_4 :
            C1Counter = _sage_const_0 
            C2Counter = _sage_const_0 
            C3Counter = _sage_const_0 
            C4Counter = _sage_const_0 
            C5Counter = _sage_const_0 
            C6pCounter = _sage_const_0 
            C6klmCounter = _sage_const_0 
            C7Counter = _sage_const_0 
            C8Counter = _sage_const_2  * self.tpp
            return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
    
    def get_power_map_counts(self):
        maps = {}
        families = ['1', '2', '3^l', '4^k', '5^k', "6'", "6^klm", "7^k", "8^k"]
        maps['1'] = dict(zip(families, self.C_1_power()))
        maps['2'] = dict(zip(families, self.C_2_power()))
        maps['3^l'] = dict(zip(families, self.C_3_power()))
        maps['4^k'] = dict(zip(families, self.C_4_power()))
        maps['5^k'] = dict(zip(families, self.C_5_power()))
        maps["6'"] = dict(zip(families, self.C_6_p_power()))
        maps["6^klm"] = dict(zip(families, self.C_6_klm_power()))
        maps["7^k"] = dict(zip(families, self.C_7_power()))
        maps["8^k"] = dict(zip(families, self.C_8_power()))
        mod_needed = {_sage_const_2 : _sage_const_12 , _sage_const_3 : _sage_const_36 , _sage_const_4 : _sage_const_72 }
        for key in maps.keys():
            for key2 in maps:
                k = var('k')
                assume(k, 'integer')
                assume(k >= _sage_const_0 )
                
                if str(type(maps[key][key2].subs(q=(self.modulus + mod_needed[self.power]*k)))) == "<class 'sage.symbolic.expression.Expression'>":
                    maps[key][key2] = maps[key][key2].subs(q=(self.modulus + mod_needed[self.power]*k)).full_simplify().subs(k=(q-self.modulus)/mod_needed[self.power]).full_simplify()
                # print(total.subs(q=(modulus + 72*k)).full_simplify().subs(k=(q-modulus)/72).full_simplify())
        return maps
    def calc_sym_power(self):
        
        total = _sage_const_0 
        if self.power == _sage_const_2 :
            square_maps = self.get_power_map_counts()
            for family in self.families:
                total += self.class_sizes[family]*self.num_classes[family]*(self.character_val[family] ** _sage_const_2 )
                for fam2 in self.families: # iterate through the maps 
                    total += self.class_sizes[family]*self.character_val[fam2]*square_maps[family][fam2]
            total = (total/_sage_const_2 )/(self.q**_sage_const_3  * self.rp * self.r * self.s * self.t)
        if self.power == _sage_const_3 :
            self_sym_squared = sym_object(self.modulus % _sage_const_12 , _sage_const_2 )
            square_maps = self_sym_squared.get_power_map_counts()
            cube_maps = self.get_power_map_counts()
            for family in self.families:
                total += self.class_sizes[family]*self.num_classes[family]*(self.character_val[family] ** _sage_const_3 )
                for fam2 in self.families: # iterate through the square maps 
                    total += self.class_sizes[family]*self.character_val[fam2]* square_maps[family][fam2] * _sage_const_3  * self.character_val[family]
                    total += self.class_sizes[family]*self.character_val[fam2]* cube_maps[family][fam2] * _sage_const_2  
            total = (total/_sage_const_6 )/(self.q**_sage_const_3  * self.rp * self.r * self.s * self.t)
        if self.power == _sage_const_4 :
            self_sym_squared = sym_object(self.modulus % _sage_const_12 , _sage_const_2 )
            square_maps = self_sym_squared.get_power_map_counts()
            self_sym_cubed = sym_object(self.modulus % _sage_const_36 , _sage_const_3 )
            cube_maps = self_sym_cubed.get_power_map_counts()
            fourth_maps = self.get_power_map_counts()
            for family in self.families:
                total += self.class_sizes[family]*self.num_classes[family]*(self.character_val[family] ** _sage_const_4 )
                for fam2 in self.families: # iterate through the square maps 
                    total += self.class_sizes[family]*self.character_val[fam2]* square_maps[family][fam2] * (self.character_val[family] ** _sage_const_2 ) * _sage_const_6 
                    total += self.class_sizes[family]*(self.character_val[fam2]** _sage_const_2 ) * square_maps[family][fam2] * _sage_const_3  
                    total += self.class_sizes[family]*self.character_val[fam2]* cube_maps[family][fam2] * self.character_val[family] * _sage_const_8 
                    total += self.class_sizes[family]*self.character_val[fam2]*fourth_maps[family][fam2] * _sage_const_6 
            total = (total/_sage_const_24 )/(self.q**_sage_const_3  * self.rp * self.r * self.s * self.t)
        return total.full_simplify()

for i in range(_sage_const_12 ):
    group = sym_object(i, _sage_const_2 )
    
    print(f"2nd sym power for q = {i} mod 12: {group.calc_sym_power()}")

for i in range(_sage_const_36 ):
    group = sym_object(i, _sage_const_3 )
    
    print(f"3rd sym power for q = {i} mod 36: {group.calc_sym_power()}")

for i in range(_sage_const_72 ):
    group = sym_object(i, _sage_const_4 )
    
    print(f"4th sym power for q = {i} mod 72: {group.calc_sym_power()}")

