

# This file was *autogenerated* from the file PSU_3_P.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_6 = Integer(6); _sage_const_50 = Integer(50); _sage_const_9 = Integer(9); _sage_const_12 = Integer(12)
from math import gcd
import time

load("group_characters.sage")
class GroupCharactersPSU3(GroupCharacters):
    q = _sage_const_1 
    p = _sage_const_0 
    d = _sage_const_0 
    r = _sage_const_0 
    s = _sage_const_0 
    t = _sage_const_0 
    tp = _sage_const_0 
    rp = _sage_const_0  
    characteristic = _sage_const_1 
    name = ""
    classes = []
    class_order = {}
    centralizer_order = {}
    group_order = _sage_const_0 
    primes = []
    power_map = {}
    characters = []
    minimal_perm = _sage_const_0 
    name = ""

    def __init__(self, prime, exp):
        start_pm_time = time.time()
        ### useful constants
        self.q = prime**exp
        self.characteristic = prime
        q = self.q
        self.p = prime
        p = self.p
        self.d = gcd(_sage_const_3 ,q+_sage_const_1 )
        d = self.d
        r = q+_sage_const_1 
        s = q-_sage_const_1 
        t = q**_sage_const_2 -q+_sage_const_1 
        rp = r//d
        tp = t//d
        self.tp = tp
        self.rp = rp
        self.s = s
        self.r = r
        self.t = t
        self.group_order = q**_sage_const_3 *r**_sage_const_2 *s*tp
        self.exp = exp

        self.name = f"PSU({prime},{exp}) (prime, exp)"

        ### conjugacy classes, class orders, and centralizer orders
        self.classes = [ "C_1", "C_2" ]
        self.class_order["C_1"] = _sage_const_1 
        self.centralizer_order["C_1"] = q**_sage_const_3 *rp*r*s*t
        self.class_order["C_2"] = p
        self.centralizer_order["C_2"] = q**_sage_const_3 *rp

        for l in range(d):
            c = f"C_3^{l}"
            self.classes.append(c)
            ### These class_orders are conjectured but not certain 
            if prime == _sage_const_2 :
                self.class_order[c] = _sage_const_4 
            else:
                self.class_order[c] = prime
            self.centralizer_order[c] = q**_sage_const_2 

        for k in range(_sage_const_1 ,rp):
            c = f"C_4^{k}"
            self.classes.append(c)
            self.class_order[c] = rp//gcd(rp,k)
            self.centralizer_order[c] = q*rp*r*s

        for k in range(_sage_const_1 ,rp):
            c = f"C_5^{k}"
            self.classes.append(c)
            self.class_order[c] = _sage_const_0 
            self.centralizer_order[c] = q*rp
            n = _sage_const_1 
            while True: # this sucks, we should find a better way to do this
                if k*n % ((q+_sage_const_1 )//d) == _sage_const_0  and n%p == _sage_const_0 :
                    self.class_order[c] = n
                    break
                n += _sage_const_1 
        if d == _sage_const_3 :
            self.classes.append("C_6'")
            self.class_order["C_6'"] = _sage_const_3 
            self.centralizer_order["C_6'"] = r**_sage_const_2 

        for l in range(_sage_const_2 ,rp+_sage_const_1 ):
            for k in range(_sage_const_1 ,l):
                m = (-k-l)%r
                if m == _sage_const_0 :
                    m = r
                if l < m:
                    
                    c = f"C_6^{{{k},{l},{m}}}"
                    self.classes.append(c)
                    self.centralizer_order[c] = rp*r
                    """
                    # there is definitely a better way to do this (Pablo's formula?)
                    # (and we need to know it) but this works for now
                    n = 1
                    while True: # heheheh
                        n += 1
                        cn = self.power_of(c,n)
                        if cn[2] == "4":
                            self.class_order[c] = n*self.class_order[cn]
                            break
                        if cn[2] == "1":
                            self.class_order[c] = n
                            break
                    """
                    # This was taking a while so I've replaced it with a maybe incorrect formula
                    self.class_order[c] = int(r / gcd(k,l,m,r))
                    
        klist = []
        for k in range(_sage_const_1 ,rp*s):
            if k%s == _sage_const_0 :
                continue
            k = min(k, ((-q*k) % (rp * s)))
            if k in klist:
                continue
            else: 
                klist.append(k)
            c = f"C_7^{k}" 
            self.classes.append(c)
            self.class_order[c] = rp*s // gcd(k, rp*s)
            self.centralizer_order[c] = rp*s

        klist = []
        for k in range(_sage_const_1 ,tp):
            k = min(k, (-k * q) % tp, ((q ** _sage_const_2 ) * k) % tp )
            if k in klist:
                continue 
            else: 
                klist.append(k)
            c = f"C_8^{k}"
            self.classes.append(c)
            self.class_order[c] = tp
            self.centralizer_order[c] = tp


        ### compute relevant primes
        # there MUST be a better way to do this
        self.primes = primes_up_to(max(self.class_order.values()))


        ### compute power maps
        # this is NOT a good way to do it, but it'll do (for known powers) for now
        for g in self.classes:
            self.power_map[g] = {}
            #for p in self.primes:
            for p in [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ]: # we only need primes up to the # of molien coefficients we're asking for.
                self.power_map[g][p] = self.power_of(g,p)
        print(f"Power Map and Class Initialization took {time.time() - start_pm_time}")
        ### implement characters of degree qs and t
        # Generates character table data for Chi_qs and Chi_t^(u)
        start_char_time = time.time()
        UCF = UniversalCyclotomicField() 
        eps = UCF.gen(r) # epsilon as an rth root of unity
        self.characters = [{} for u in range(rp)] 
        for g in self.classes:
            i = int(g[_sage_const_2 ]) 
            k,l,m = _sage_const_0 ,_sage_const_0 ,_sage_const_0  
            if i in [_sage_const_3 ,_sage_const_4 ,_sage_const_5 ,_sage_const_7 ,_sage_const_8 ]:
                k = int(g[_sage_const_4 :])
            elif i == _sage_const_6  and g[-_sage_const_1 ] != "'":
                k,l,m = map(int,g[_sage_const_5 :-_sage_const_1 ].split(','))
            if i == _sage_const_1 : 
                self.characters[_sage_const_0 ][g] = q * s 
            elif i == _sage_const_2 : 
                self.characters[_sage_const_0 ][g] = -q
            elif i == _sage_const_3 : 
                self.characters[_sage_const_0 ][g] = _sage_const_0  
            elif i == _sage_const_4 : 
                self.characters[_sage_const_0 ][g] = -s
            elif i == _sage_const_5 : 
                self.characters[_sage_const_0 ][g] = _sage_const_1  
            elif i == _sage_const_6 : 
                self.characters[_sage_const_0 ][g] = _sage_const_2 
            elif i == _sage_const_7 : 
                self.characters[_sage_const_0 ][g] = _sage_const_0 
            elif i == _sage_const_8 : 
                self.characters[_sage_const_0 ][g] = -_sage_const_1 
            for u in range(_sage_const_1 ,rp):
                if i == _sage_const_1 : 
                    self.characters[u][g] = t 
                elif i == _sage_const_2 : 
                    self.characters[u][g] = -s 
                elif i == _sage_const_3 : 
                    self.characters[u][g] = _sage_const_1 
                elif i == _sage_const_4 : 
                    self.characters[u][g] = -s * eps**(_sage_const_3  * u * k) + eps**(-_sage_const_6  * u * k)  
                elif i == _sage_const_5 : 
                    self.characters[u][g] = eps**(_sage_const_3  * u * k) + eps**(-_sage_const_6  * u * k) 
                elif i == _sage_const_6  : 
                    if g[-_sage_const_1 ] == "'": 
                        self.characters[u][g] = _sage_const_3 
                    else: 
                        self.characters[u][g] = eps**(_sage_const_3  * u * k) + eps**(_sage_const_3  * u * l) + eps**(_sage_const_3  * u * m) 
                elif i == _sage_const_7 : 
                    self.characters[u][g] = eps**(_sage_const_3  * u * k) 
                elif i == _sage_const_8 : 
                    self.characters[u][g] = _sage_const_0  
        print(f"Character Table took {time.time() - start_char_time}")
            # return self.characters #end of check for our 2 chars 


        if self.q == _sage_const_5 :
            self.minimal_perm = _sage_const_50 
        else:
            self.minimal_perm = self.q ** _sage_const_3  + _sage_const_1   

    def power_of(self, g, n):
        """
        computes the conjugacy class of g^n
        """
        q = self.q
        d = self.d
        s = q - _sage_const_1 
        r = (q + _sage_const_1 ) // d
        tp = self.tp
        rp = self.rp
        p = self.characteristic
        i = int(g[_sage_const_2 ])

        # initialize
        k,l,m = _sage_const_0 ,_sage_const_0 ,_sage_const_0  

        # string handling to recover indices from string
        # we'll use this when computing characters, but annoying to package as a function
        if i in [_sage_const_3 ,_sage_const_4 ,_sage_const_5 ,_sage_const_7 ,_sage_const_8 ]:
            k = int(g[_sage_const_4 :])
        elif i == _sage_const_6  and g[-_sage_const_1 ] != "'":
            k,l,m = map(int,g[_sage_const_5 :-_sage_const_1 ].split(','))

        # power map logic
        if i == _sage_const_1 :
            return "C_1"
        elif i == _sage_const_2 :
            if n%p == _sage_const_0 :
                return "C_1"
            return "C_2"
        elif i == _sage_const_3 :
            if self.characteristic == _sage_const_2 :
                if n%_sage_const_4  == _sage_const_0 :
                    return "C_1"
                elif n%_sage_const_2  == _sage_const_0 :
                    return "C_2"
                else:
                    return g 
            else:
                if n%self.characteristic == _sage_const_0 :
                    return "C_1"
                else:
                    return g 
        elif i == _sage_const_4 :
            e = (n*k) % ((q+_sage_const_1 )//d)
            if e == _sage_const_0 :
                return "C_1"
            else:
                return f"C_4^{e}"
        elif i == _sage_const_5 :
            if k*n % ((q+_sage_const_1 )//d) == _sage_const_0  and n%p == _sage_const_0  :
                return "C_1"
            elif k*n % ((q+_sage_const_1 )//d) == _sage_const_0 :
                return "C_2"
            elif n % p == _sage_const_0 :
                return f"C_4^{n * k % rp}" # added 7/15--might not  work
            return f"C_5^{k*n % ((q+_sage_const_1 )//d)}"
        elif i == _sage_const_6 :
            # Logic for C_6'
            if g[-_sage_const_1 ] == "'":
                if n%_sage_const_3  == _sage_const_0 :
                    return "C_1"
                return "C_6'"
            # Logic for C_6^{k,l,m}
            diag = [(n*x)%((q+_sage_const_1 )) for x in (k,l,m)] # ((q+1)//d) ?
            k,l,m = sorted([ (q+_sage_const_1 ) if x == _sage_const_0  else x for x in diag])  # ((q+1)//d) ?

            if (k,l,m) == ((q+_sage_const_1 )//d, _sage_const_2  * ((q+_sage_const_1 )//d),  (q+_sage_const_1 )): # checks for C_6'
                return "C_6'" 
            while l > (q+_sage_const_1 )//d:
                diag  = [(x + (q+_sage_const_1 )//d)%(q+_sage_const_1 ) for x in (k,l,m)]
                k,l,m = sorted([ (q+_sage_const_1 ) if x == _sage_const_0  else x for x in diag])
                

            if k == l or l == m: # broke the rules!
                return self.power_of(f"C_4^1", l) # what's up with this?
            return f"C_6^{{{k},{l},{m}}}"
        elif i == _sage_const_7 :
            if k*n % (s*rp) == _sage_const_0 :
                return "C_1"
            elif k*n % s == _sage_const_0 :
                return f"C_4^{sorted([s*k*n % (s*rp), k*n % (s*rp), (-q*k*n) % (s*rp)])[_sage_const_1 ] // s}"
            y = k*n % (s*rp)
            y = min(y, (-q*y) % (s*rp))
            return f"C_7^{y}"
        elif i == _sage_const_8 :
            if k*n % tp == _sage_const_0 :
                return "C_1"
            w = k*n % tp
            w = min(w, w*(-q) % tp, w*q*q % tp)
            return f"C_8^{w}"
    
    def C_1_squared(self):
        C1Counter = _sage_const_1 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
    
    def C_1_cubed(self):
        C1Counter = _sage_const_1 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_1_forth(self):
        C1Counter = _sage_const_1 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
    
    def C_2_squared(self):
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_1 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        p = self.p
        if p == _sage_const_2 :
            C1Counter += _sage_const_1 
            C2Counter -= _sage_const_1 
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_2_cubed(self):
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_1 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        p = self.p
        if p == _sage_const_3 :
            C1Counter += _sage_const_1 
            C2Counter -= _sage_const_1 
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_2_forth(self):
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_1 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        p = self.p
        if p == _sage_const_2 :
            C1Counter += _sage_const_1 
            C2Counter -= _sage_const_1 
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_3_squared(self):
        d = self.d
        p = self.p
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_0 
        C3Counter = d
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        if p == _sage_const_2 :
            C2Counter += d
            C3Counter -= d
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    
    def C_3_cubed(self):
        d = self.d
        p = self.p
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_0 
        C3Counter = d
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        if p == _sage_const_3 :
            C1Counter += d
            C3Counter -= d
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    
    def C_3_forth(self):
        d = self.d
        p = self.p
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_0 
        C3Counter = d
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        if p == _sage_const_2 :
            C1Counter += d
            C3Counter -= d
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_4_squared(self):
        q = self.q
        d = self.d
        C1Counter = _sage_const_0 
        C4Counter = (q+_sage_const_1 )//d-_sage_const_1 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        if q % _sage_const_2  == _sage_const_1 :
            C1Counter += _sage_const_1 
            C4Counter -= _sage_const_1 
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_4_cubed(self):
        q = self.q
        d = self.d
        C1Counter = _sage_const_0 
        C4Counter = (q+_sage_const_1 )//d-_sage_const_1 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        if (q+_sage_const_1 ) % _sage_const_9  == _sage_const_0 :
            C1Counter += _sage_const_2 
            C4Counter -= _sage_const_2 
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_4_forth(self):
        q = self.q
        d = self.d
        C1Counter = _sage_const_0 
        C4Counter = (q+_sage_const_1 )//d-_sage_const_1 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        if (q+_sage_const_1 ) % _sage_const_4  == _sage_const_0 : 
            C1Counter += _sage_const_3 
            C4Counter -= _sage_const_3 
        elif (q+_sage_const_1 ) % _sage_const_2  == _sage_const_0 :
            C1Counter += _sage_const_1 
            C4Counter -= _sage_const_1 
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_5_squared(self):
        q = self.q
        d = self.d
        p = self.p
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = (q+_sage_const_1 )//d-_sage_const_1 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        if q % _sage_const_2  == _sage_const_1 :
            C2Counter +=_sage_const_1 
            C5Counter -= _sage_const_1 
        if p == _sage_const_2 :
            C4Counter += (q+_sage_const_1 )//d-_sage_const_1 
            C5Counter -= (q+_sage_const_1 )//d-_sage_const_1 
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_5_cubed(self):
        q = self.q
        d = self.d
        p = self.p
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = (q+_sage_const_1 )//d-_sage_const_1 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        if (q+_sage_const_1 ) % _sage_const_9  == _sage_const_0 :
            C2Counter += _sage_const_2 
            C5Counter -= _sage_const_2 
        if p == _sage_const_3 :
            C4Counter += (q+_sage_const_1 )//d-_sage_const_1 
            C5Counter-= (q+_sage_const_1 )//d-_sage_const_1  
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_5_forth(self):
        q = self.q
        d = self.d
        p = self.p
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = (q+_sage_const_1 )//d-_sage_const_1 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        if (q+_sage_const_1 ) % _sage_const_2  == _sage_const_0 :
            C2Counter += _sage_const_1 
            C5Counter -= _sage_const_1 
        if p == _sage_const_2 :
            C4Counter += (q+_sage_const_1 )//d-_sage_const_1 
            C5Counter-= (q+_sage_const_1 )//d-_sage_const_1  
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_6_p_squared(self):
        d = self.d
        C6pCounter = _sage_const_1 -(_sage_const_3 -d)//_sage_const_2 
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_6_p_cubed(self):
        d = self.d
        C6pCounter = _sage_const_0 
        C1Counter = _sage_const_1 -(_sage_const_3 -d)//_sage_const_2 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_6_p_forth(self):
        d = self.d
        C6pCounter = _sage_const_1 -(_sage_const_3 -d)//_sage_const_2 
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = _sage_const_0 

        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)


    def C_6_klm_sym_squared(self):
        C4Counter = _sage_const_0 
        C1Counter = _sage_const_0 
        r = self.r
        if self.r % _sage_const_3  != _sage_const_0 :
            if self.r % _sage_const_2  == _sage_const_1 :
                pass
            else:
                # Case 1b
                k = math.ceil(r/_sage_const_4 )
                while k < r/_sage_const_3 :
                    k += _sage_const_1 
                    C4Counter += _sage_const_1 
                # Case 3a
                k = _sage_const_1 
                while k < r/_sage_const_6 :
                    k += _sage_const_1 
                    C4Counter += _sage_const_1 
                # Case 3b
                k = math.ceil(r/_sage_const_3 )
                while k < r/_sage_const_2 :
                    k += _sage_const_1 
                    C4Counter += _sage_const_1 
                # Case 2a 
                if self.r % _sage_const_4  == _sage_const_0 :
                    k = _sage_const_1 
                    while k < r/_sage_const_6 :
                        if k % _sage_const_2  == _sage_const_0 :
                            C4Counter += _sage_const_1 
                        k += _sage_const_1 
                else: 
                    k = _sage_const_1 
                    while k < r/_sage_const_6 :
                        if k % _sage_const_2  == _sage_const_1 :
                            C4Counter += _sage_const_1 
                        k += _sage_const_1 
        # d = 3 case
        else: 
            # Case 3a
            k = math.ceil(r/_sage_const_12 )
            while k < r/_sage_const_6 :
                k += _sage_const_1 
                C4Counter += _sage_const_1 
            # Case 2a 
            if self.r % _sage_const_4  == _sage_const_0 :
                k = _sage_const_1 
                while k < r/_sage_const_6 :
                    if k % _sage_const_2  == _sage_const_0 :
                        C4Counter += _sage_const_1 
                    k += _sage_const_1 
            else: 
                k = _sage_const_1 
                while k < r/_sage_const_6 :
                    if k % _sage_const_2  == _sage_const_1 :
                        C4Counter += _sage_const_1 
                    k += _sage_const_1 

        return C4Counter

    def C_6_klm_sym_cubed(self):
        C4Counter = _sage_const_0  
        r = self.r 
        if r % _sage_const_3  != _sage_const_0 :
            pass
        else: 
            # Case 2a
            k = math.ceil(r/_sage_const_6 )
            while k < _sage_const_2 *r/_sage_const_9 :
                C4Counter += _sage_const_1 
                k += _sage_const_1  
            # Case 3a 
            k = _sage_const_1 
            while k < _sage_const_2 *r/_sage_const_9 :
                if k % _sage_const_2  == _sage_const_0 :
                    C4Counter += _sage_const_1 
                k += _sage_const_1 
            # Case 2a, 3a difference = 2r/3
            k = _sage_const_1 
            while k < r/_sage_const_9 :
                C4Counter += _sage_const_1 
                if r % _sage_const_6  == _sage_const_0  and k % _sage_const_2  == _sage_const_0 :
                    C4Counter += _sage_const_1 
                elif r % _sage_const_6  == _sage_const_3  and k % _sage_const_2  == _sage_const_1 :
                    C4Counter += _sage_const_1 
                k += _sage_const_1 

        return C4Counter
    
    def C_7_squared(self):
        p = self.p
        q = self.q
        d = self.d
        totalnum = (q*q-q+_sage_const_1 -d)//(_sage_const_2 *self.d) - (_sage_const_3 -d)//_sage_const_2 
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = totalnum
        C8Counter = _sage_const_0 
        if q % _sage_const_2  != _sage_const_0 :
            C4Counter += (q+_sage_const_1 )//(_sage_const_2 *self.d)
            C7Counter = C7Counter - (q+_sage_const_1 )//(_sage_const_2 *self.d)
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_7_cubed(self):
        p = self.p
        q = self.q
        d = self.d
        totalnum = (q*q-q+_sage_const_1 -d)//(_sage_const_2 *self.d) - (_sage_const_3 -d)//_sage_const_2 
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = totalnum
        C8Counter = _sage_const_0 
        if q % _sage_const_3  == _sage_const_1 :
            C1Counter += _sage_const_1 
            C7Counter -= _sage_const_1 
            C4Counter += q
            C7Counter -= q
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)

    def C_7_forth(self):
        p = self.p
        q = self.q
        d = self.d
        totalnum = (q*q-q+_sage_const_1 -d)//(_sage_const_2 *self.d) - (_sage_const_3 -d)//_sage_const_2 
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = totalnum
        C8Counter = _sage_const_0 
        if q % _sage_const_2  != _sage_const_0 :
            C1Counter += _sage_const_1 
            C7Counter -= _sage_const_1 
        if q % _sage_const_4  == _sage_const_1 :
            C4Counter += (q+_sage_const_1 )//(_sage_const_2 *self.d)
            C7Counter -= (q+_sage_const_1 )//(_sage_const_2 *self.d)
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
    
    def C_8_squared(self):
        q = self.q
        d = self.d
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = ((q*q-q+_sage_const_1 )//d-_sage_const_1 )//_sage_const_3 
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
    
    def C_8_cubed(self):
        q = self.q
        d = self.d
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = ((q*q-q+_sage_const_1 )//d-_sage_const_1 )//_sage_const_3 
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
    
    def C_8_forth(self):
        q = self.q
        d = self.d
        C1Counter = _sage_const_0 
        C2Counter = _sage_const_0 
        C3Counter = _sage_const_0 
        C4Counter = _sage_const_0 
        C5Counter = _sage_const_0 
        C6pCounter = _sage_const_0 
        C6klmCounter = _sage_const_0 
        C7Counter = _sage_const_0 
        C8Counter = ((q*q-q+_sage_const_1 )//d-_sage_const_1 )//_sage_const_3 
        return (C1Counter, C2Counter, C3Counter, C4Counter, C5Counter, C6pCounter, C6klmCounter, C7Counter, C8Counter)
            



def primes_up_to(k):
    """
    returns an ascending list of all primes up through k
    """
    primes = [_sage_const_2 ]
    for i in range(_sage_const_3 ,k):
        for p in primes:
            if i%p == _sage_const_0 : break
        else:
            primes.append(i)
    return(primes)

start = time.time()






# G = GroupCharactersPSU3(3,6)
# print(G.class_order)
# G.display()
# print(G.the_game(G.characters[0], 10))
# H = GroupCharacters("PSU(3, 3)")
# print(H.the_game(H.characters[1], 10))
# print(H.the_game(H.characters[1], 10))
# H.display()

# currently fails for q = 125, 4, 8, 3, 7, 27 -- struggling with third powers, small primes, and a couple other things?
# Works for: q = 2, 5, 25, 16, 32, 49, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47

end = time.time()
print(f"Elapsed time: {end - start:.4f} seconds")   
i = _sage_const_0 
G = GroupCharactersPSU3(_sage_const_2 , _sage_const_3 )
for g in G.classes:
    if g[_sage_const_2 ] == "6":
        if G.power_of(g, _sage_const_2 )[_sage_const_2 ] != "6":
            print(g)
            print(f"g squared is {G.power_of(g, _sage_const_2 )}")
            i += _sage_const_1 
print(i)
print(G.C_6_klm_sym_squared())


i1 = _sage_const_0 
i2 = _sage_const_0 
i3 = _sage_const_0 
i4 = _sage_const_0 
i5 = _sage_const_0 
i6p = _sage_const_0 
i6klm = _sage_const_0 
i7 = _sage_const_0 
i8 = _sage_const_0 
for g in G.classes:
    if g[_sage_const_2 ] == "3":
        pw = _sage_const_2 
        if G.power_of(g, pw)[_sage_const_2 ] == "1":
            i1 += _sage_const_1 
        if G.power_of(g, pw)[_sage_const_2 ] == "2":
            i2 += _sage_const_1 
        if G.power_of(g, pw)[_sage_const_2 ] == "3":
            i3 += _sage_const_1 
        if G.power_of(g, pw)[_sage_const_2 ] == "4":
            i4 += _sage_const_1 
        if G.power_of(g, pw)[_sage_const_2 ] == "5":
            i5 += _sage_const_1 
        if G.power_of(g, pw)[_sage_const_2 ] == "":
            i6p += _sage_const_1 
        if G.power_of(g, pw)[_sage_const_2 ] == "6":
            i6klm += _sage_const_1 
        if G.power_of(g, pw)[_sage_const_2 ] == "7":
            i7 += _sage_const_1 
        if G.power_of(g, pw)[_sage_const_2 ] == "8":
            i8 += _sage_const_1 
print(f"emperical problem cases (to the {pw}st/nd/th power): {i1, i2, i3, i4, i5, i6p, i6klm, i7, i8}")
print(f"predicted problem cases (to the {pw}st/nd/th power): {G.C_3_squared()}")

# so, this doesn't quite work. I don't know what's going on here but it looks like we're undercounting by 1 or 2 sometimes but asymptotically we're overcounting? 

