

# This file was *autogenerated* from the file analysis.sage
from sage.all_cmdline import *   # import sage library

import json

# Load the data
with open("data.json") as f:
    data = json.load(f)

# Filter for PSU(2,1) (prime, exp) entries
target_group = "PSU(2,1) (prime, exp)"
filtered = [entry for entry in data if entry["group"] == target_group]

# Find the entry with the minimum bound
min_entry = min(filtered, key=lambda x: x["bound"])

# Print the result
print(f"Character index with min bound: {min_entry['character_index']}")
print(f"Min bound: {min_entry['bound']}")


